-- Insert all unique family names into the species_family table
INSERT INTO species_family (name)
VALUES
    ('POLYPTERIDAE'),
    ('OPHIDIIDAE'),
    ('GLYPHEIDAE'),
    ('GEOTRIIDAE'),
    ('PHAETHONTIDAE'),
    ('HAEMATOCOCCACEAE'),
    ('EUNICIDAE'),
    ('PHALACROCORACIDAE'),
    ('LYSIOSQUILLIDAE'),
    ('CETORHINIDAE'),
    ('BALITORIDAE'),
    ('LATIMERIIDAE'),
    ('PHREATOBIIDAE'),
    ('THYSANOTEUTHIDAE'),
    ('ACIPENSERIDAE'),
    ('CORALLIIDAE'),
    ('GECARCINIDAE'),
    ('POLYPRIONIDAE'),
    ('TRAPEZIIDAE'),
    ('CHIROCENTRIDAE'),
    ('CHAMIDAE'),
    ('CORYSTIDAE'),
    ('NEMALIACEAE'),
    ('RIVULIDAE'),
    ('BIEMNIDAE'),
    ('ANACANTHOBATIDAE'),
    ('OLIVIDAE'),
    ('ODONTASPIDIDAE'),
    ('VERMETIDAE'),
    ('BRAMIDAE'),
    ('RHAMPHICHTHYIDAE'),
    ('DIODONTIDAE'),
    ('CALYPTRAEIDAE'),
    ('PHASCOLOSOMATIDAE'),
    ('PRISTIGASTERIDAE'),
    ('KALLYMENIACEAE'),
    ('ELEGINOPIDAE'),
    ('GERYONIDAE'),
    ('ACARNIDAE'),
    ('PARALEPIDIDAE'),
    ('SEPIADARIIDAE'),
    ('TOXOTIDAE'),
    ('SCOMBROPIDAE'),
    ('CARCHARIIDAE'),
    ('TRICHECHIDAE'),
    ('SCHIZASTERIDAE'),
    ('PLEUROBRANCHIDAE'),
    ('ULMARIDAE'),
    ('TURBINIDAE'),
    ('CURIMATIDAE'),
    ('PODICIPEDIDAE'),
    ('BADIDAE'),
    ('EUSIRIDAE'),
    ('OCTOPOTEUTHIDAE'),
    ('BATHYCLUPEIDAE'),
    ('CHANNICHTHYIDAE'),
    ('EPIALTIDAE'),
    ('CANCRIDAE'),
    ('ARCIDAE'),
    ('PSEUDOTRIAKIDAE'),
    ('BYTHITIDAE'),
    ('TRICHOMYCTERIDAE'),
    ('FISSURELLIDAE'),
    ('HOWELLIDAE'),
    ('HETERODONTIDAE'),
    ('DENTATHERINIDAE'),
    ('TINCIDAE'),
    ('AMARSIPIDAE'),
    ('COELOSPHAERIDAE'),
    ('TRIONYCHIDAE'),
    ('LEBIASINIDAE'),
    ('ARCHITECTONICIDAE'),
    ('OMMASTREPHIDAE'),
    ('ANTENNARIIDAE'),
    ('CARDIIDAE'),
    ('ESCHRICHTIIDAE'),
    ('DUMONTIACEAE'),
    ('LARIDAE'),
    ('PORANIIDAE'),
    ('CHORDARIACEAE'),
    ('CYPERACEAE'),
    ('POMATOMIDAE'),
    ('ELEOTRIDAE'),
    ('THALASSELEOTRIDIDAE'),
    ('LATEOLABRACIDAE'),
    ('GURGESIELLIDAE'),
    ('HOMOLIDAE'),
    ('TRACHIPTERIDAE'),
    ('DORIDIDAE'),
    ('CHIROSTYLIDAE'),
    ('PALLENOPSIDAE'),
    ('ANTARCTURIDAE'),
    ('BEMBROPIDAE'),
    ('EVERMANNELLIDAE'),
    ('ACHEILOGNATHIDAE'),
    ('GRAMMICOLEPIDIDAE'),
    ('PERCOPHIDAE'),
    ('CHIASMODONTIDAE'),
    ('DREPANEIDAE'),
    ('NELUMBONACEAE'),
    ('TROCHIDAE'),
    ('POLYCHELIDAE'),
    ('AEQUOREIDAE'),
    ('CALIGIDAE'),
    ('GLAUCOSOMATIDAE'),
    ('SPONGIIDAE'),
    ('GALEOCERDONIDAE'),
    ('CHLOPSIDAE'),
    ('LEPTOTHECATA (LEPTOMEDUSAE)'),
    ('BANGIACEAE'),
    ('ALCEDINIDAE'),
    ('PLEURONECTIDAE'),
    ('FICIDAE'),
    ('NIPHONIDAE'),
    ('CHANNIDAE'),
    ('CRANOGLANIDIDAE'),
    ('NEOSEBASTIDAE'),
    ('HANLEYIDAE'),
    ('DENDROPHYLLIIDAE'),
    ('SEMELIDAE'),
    ('SYMPHYSANODONTIDAE'),
    ('MACROPHTHALMIDAE'),
    ('DICHISTIIDAE'),
    ('CLARIIDAE'),
    ('CYCLOPSETTIDAE'),
    ('LITHOPHYLLACEAE'),
    ('RISSOIDAE'),
    ('LEPTOCHITONIDAE'),
    ('CELLEPORIDAE'),
    ('COBITIDAE'),
    ('ALBUNEIDAE'),
    ('GOBIIDAE'),
    ('PHOLADIDAE'),
    ('AHNFELTIACEAE'),
    ('FLABELLIDAE'),
    ('TELMATOBIIDAE'),
    ('MORIDAE'),
    ('CYRENIDAE'),
    ('HIPPOLYTIDAE'),
    ('MYCALIDAE'),
    ('CHLORELLACEAE'),
    ('PHYLLOPHORACEAE'),
    ('CAMPYLONOTIDAE'),
    ('HILDENBRANDIACEAE'),
    ('CAPNEIDAE'),
    ('KOGIIDAE'),
    ('PSEUDOCARCHARIIDAE'),
    ('PASIPHAEIDAE'),
    ('CALLITHAMNIACEAE'),
    ('GLYCERIDAE'),
    ('LAMINARIACEAE'),
    ('GRYPHAEIDAE'),
    ('PANTODONTIDAE'),
    ('SCOLOPACIDAE'),
    ('MARGARITIFERIDAE'),
    ('DIOMEDEIDAE'),
    ('MEGACHASMIDAE'),
    ('HIMANTHALIACEAE'),
    ('NEMATISTIIDAE'),
    ('STICHASTERIDAE'),
    ('SCOMBERESOCIDAE'),
    ('OGYRIDIDAE'),
    ('OPISTHOCENTRIDAE'),
    ('APLODACTYLIDAE'),
    ('CENTRARCHIDAE'),
    ('PECTINARIIDAE'),
    ('SAMARIDAE'),
    ('LINOPHRYNIDAE'),
    ('BREGMACEROTIDAE'),
    ('CLUPEIDAE'),
    ('MOLGULIDAE'),
    ('DENTICIPITIDAE'),
    ('PLATYRHINIDAE'),
    ('OSTRACIIDAE'),
    ('DACTYLOSCOPIDAE'),
    ('PHARIDAE'),
    ('ACANTHURIDAE'),
    ('PLOTOSIDAE'),
    ('DICTYOTACEAE'),
    ('POTAMIDIDAE'),
    ('RANINIDAE'),
    ('LESSONIACEAE'),
    ('TRIPORTHEIDAE'),
    ('TURBINELLIDAE'),
    ('PERCILIIDAE'),
    ('CAULOPHRYNIDAE'),
    ('CARAPIDAE'),
    ('TRIACANTHODIDAE'),
    ('MACRURONIDAE'),
    ('MYXINIDAE'),
    ('CYCLOPTERIDAE'),
    ('ANCORINIDAE'),
    ('CTENOCIDARIDAE'),
    ('ELASSOMATIDAE'),
    ('PENTACEROTIDAE'),
    ('CLAVAGELLIDAE'),
    ('LIMOPSIDAE'),
    ('MOCHOKIDAE'),
    ('BRYCONIDAE'),
    ('GALENIDAE'),
    ('GEMPYLIDAE'),
    ('ACARTIIDAE'),
    ('PHRACTOLAEMIDAE'),
    ('TEREBRIDAE'),
    ('VIRGULARIIDAE'),
    ('ICTALURIDAE'),
    ('SPHAEROCOCCACEAE'),
    ('CLAROTEIDAE'),
    ('MONACANTHIDAE'),
    ('PROTOPTILIDAE'),
    ('DACTYLOPTERIDAE'),
    ('ALBULIDAE'),
    ('MADREPORIDAE'),
    ('EUPHYLLIIDAE'),
    ('SCHIZOPATHIDAE'),
    ('CYPRINODONTIDAE'),
    ('CHIMAERIDAE'),
    ('MURAENOLEPIDIDAE'),
    ('CHALCEIDAE'),
    ('PROCATOPODIDAE'),
    ('HALICLYSTIDAE'),
    ('STRAHLAXIIDAE'),
    ('SQUALIDAE'),
    ('SOLECURTIDAE'),
    ('CLAVATULIDAE'),
    ('AMPULLARIIDAE'),
    ('SKENEIDAE'),
    ('LEPTOBARBIDAE'),
    ('TRYGONORRHINIDAE'),
    ('CENTROPHRYNIDAE'),
    ('TETILLIDAE'),
    ('DIRETMIDAE'),
    ('CALLIONYMIDAE'),
    ('LEPADIDAE'),
    ('DINEMATICHTHYIDAE'),
    ('SPONGICOLIDAE'),
    ('HETEROPNEUSTIDAE'),
    ('AUCHENOGLANIDIDAE'),
    ('AMBLYOPSIDAE'),
    ('NOETIIDAE'),
    ('TREMOCTOPODIDAE'),
    ('AORIDAE'),
    ('ERYTHRINIDAE'),
    ('GRACILARIACEAE'),
    ('ACANTHEPHYRIDAE'),
    ('LOTIDAE'),
    ('CALLANTHIIDAE'),
    ('SCOPHTHALMIDAE'),
    ('APHANIIDAE'),
    ('ALCYONIDIIDAE'),
    ('BUCCINIDAE'),
    ('VENERIDAE'),
    ('HIMANTOLOPHIDAE'),
    ('GECARCINUCIDAE'),
    ('SALMONIDAE'),
    ('CRYPTHECODINIACEAE'),
    ('ZIPHIIDAE'),
    ('ELLOBIIDAE'),
    ('PSEUDOCARCINIDAE'),
    ('RHINOCHIMAERIDAE'),
    ('URISTIDAE'),
    ('LITTORINIDAE'),
    ('ARACANIDAE'),
    ('ANOTOPTERIDAE'),
    ('ROSTELLARIIDAE'),
    ('CENTRISCIDAE'),
    ('HYPERIIDAE'),
    ('ARHYNCHOBATIDAE'),
    ('OCYTHOIDAE'),
    ('BRACHIONICHTHYIDAE'),
    ('LEPIDOSIRENIDAE'),
    ('HYMEDESMIIDAE'),
    ('ELLOPOSTOMATIDAE'),
    ('ACTEONIDAE'),
    ('PORPITIDAE'),
    ('UNIONIDAE'),
    ('SCHILBEIDAE'),
    ('MICROHYLIDAE'),
    ('NOTOCHEIRIDAE'),
    ('LOPHIIDAE'),
    ('ECHENEIDAE'),
    ('CUCUMARIIDAE'),
    ('ALPHEIDAE'),
    ('CAMAENIDAE'),
    ('BOTIIDAE'),
    ('SILLAGINIDAE'),
    ('ODONTOBUTIDAE'),
    ('NARKIDAE'),
    ('CROCODYLIDAE'),
    ('PRISTOLEPIDIDAE'),
    ('HALOSAURIDAE'),
    ('OSTEOGLOSSIDAE'),
    ('SCOMBRIDAE'),
    ('CAUDINIDAE'),
    ('CHEIMARRICHTHYIDAE'),
    ('CYEMATIDAE'),
    ('COLIDAE'),
    ('HOLOZOIDAE'),
    ('STERNOPTYCHIDAE'),
    ('CYMATIIDAE'),
    ('CONGIOPODIDAE'),
    ('LITHODIDAE'),
    ('OPHIURIDAE'),
    ('PYCNOGONIDAE'),
    ('ONCOPTERIDAE'),
    ('SERRASALMIDAE'),
    ('HISTIOTEUTHIDAE'),
    ('ONEIRODIDAE'),
    ('SCYTOSIPHONACEAE'),
    ('ASTERONYCHIDAE'),
    ('BALAENOPTERIDAE'),
    ('MYROCONGRIDAE'),
    ('INDOSTOMIDAE'),
    ('NOMEIDAE'),
    ('ARISTEIDAE'),
    ('ISOCHRYSIDACEAE'),
    ('SIPHONARIIDAE'),
    ('APHRODITIDAE'),
    ('MURAENESOCIDAE'),
    ('SPIRULIDAE'),
    ('MITSUKURINIDAE'),
    ('BENTHESICYMIDAE'),
    ('EURYPATAGIDAE'),
    ('PALINURIDAE'),
    ('GLYPHOCRANGONIDAE'),
    ('SIPUNCULIDAE'),
    ('GEOEMYDIDAE'),
    ('VALENCIIDAE'),
    ('CHILODONTIDAE'),
    ('ECHINOMETRIDAE'),
    ('EUPLECTELLIDAE'),
    ('CAPITELLIDAE'),
    ('BATHYSAURIDAE'),
    ('REGALECIDAE'),
    ('ICOSTEIDAE'),
    ('LEPISOSTEIDAE'),
    ('POLYMASTIIDAE'),
    ('MONOCENTRIDAE'),
    ('ALCIDAE'),
    ('PLACUNIDAE'),
    ('LUCINIDAE'),
    ('LYSMATIDAE'),
    ('POLYBIIDAE'),
    ('BAGRIDAE'),
    ('SACCOPHARYNGIDAE'),
    ('RHYACICHTHYIDAE'),
    ('NACELLIDAE'),
    ('NEOZOARCIDAE'),
    ('ENTEROCTOPODIDAE'),
    ('DOLIOLIDAE'),
    ('FASCIOLARIIDAE'),
    ('CERATIIDAE'),
    ('MALLETIIDAE'),
    ('NEMACHEILIDAE'),
    ('PHOCIDAE'),
    ('CICHLIDAE'),
    ('CERAMIACEAE'),
    ('AMPHIURIDAE'),
    ('GORGONOCEPHALIDAE'),
    ('CRUORIACEAE'),
    ('LOBOPHYLLIIDAE'),
    ('SCYTALINIDAE'),
    ('HOLOCENTRIDAE'),
    ('AMMODYTIDAE'),
    ('GIGANTACTINIDAE'),
    ('ASTARTIDAE'),
    ('HALYMENIACEAE'),
    ('MONOGNATHIDAE'),
    ('PROCELLARIIDAE'),
    ('ODACIDAE'),
    ('SINIPERCIDAE'),
    ('OITHONIDAE'),
    ('PANGASIIDAE'),
    ('TETRAGONURIDAE'),
    ('NYMPHONIDAE'),
    ('COSTELLARIIDAE'),
    ('MERULINIDAE'),
    ('SCIAENIDAE'),
    ('SPONGILLIDAE'),
    ('TEMNOPLEURIDAE'),
    ('CENTROPHORIDAE'),
    ('CETOPSIDAE'),
    ('LABRISOMIDAE'),
    ('MONODONTIDAE'),
    ('AMPHILIIDAE'),
    ('MALACANTHIDAE'),
    ('KYPHOSIDAE'),
    ('CHIROTEUTHIDAE'),
    ('SOLENOSTOMIDAE'),
    ('ASPREDINIDAE'),
    ('PERCICHTHYIDAE'),
    ('LIMIDAE'),
    ('SCLERITODERMIDAE'),
    ('POCILLOPORIDAE'),
    ('CONRAUIDAE'),
    ('NEOSCOPELIDAE'),
    ('ZANOBATIDAE'),
    ('PHYLLARIACEAE'),
    ('MOLIDAE'),
    ('RETROPINNIDAE'),
    ('ACROPORIDAE'),
    ('NOTACANTHIDAE'),
    ('ROMANCHEINIDAE'),
    ('PLATANISTIDAE'),
    ('PSEUDOTRICHONOTIDAE'),
    ('PARALICHTHODIDAE'),
    ('ACCIPITRIDAE'),
    ('DERMOCHELYIDAE'),
    ('GERREIDAE'),
    ('DREISSENIDAE'),
    ('LIMULIDAE'),
    ('CLAVELINIDAE'),
    ('BLENNIIDAE'),
    ('CHAETODERMATIDAE'),
    ('ZANCLORHYNCHIDAE'),
    ('MUSTELIDAE'),
    ('PAGURIDAE'),
    ('SPHYRAENIDAE'),
    ('GASTEROPELECIDAE'),
    ('PSEUDOMUGILIDAE'),
    ('CHAUNACIDAE'),
    ('TUBULARIIDAE'),
    ('ANTIPATHIDAE'),
    ('CANDIDAE'),
    ('EUCHAETIDAE'),
    ('AGLAOPHENIIDAE'),
    ('ESOCIDAE'),
    ('HOPLICHTHYIDAE'),
    ('MASTACEMBELIDAE'),
    ('MACTRIDAE'),
    ('OCEANITIDAE'),
    ('TERAPONTIDAE'),
    ('HYPOPOMIDAE'),
    ('DINOLESTIDAE'),
    ('MONOSTROMATACEAE'),
    ('ZEIDAE'),
    ('ZENARCHOPTERIDAE'),
    ('MALLEIDAE'),
    ('COLOSSENDEIDAE'),
    ('TEGULIDAE'),
    ('TRIGLIDAE'),
    ('SYNGNATHIDAE'),
    ('HISPIDOBERYCIDAE'),
    ('OPHIOTRICHIDAE'),
    ('CHARONIIDAE'),
    ('ONYCHOTEUTHIDAE'),
    ('CIRRHITIDAE'),
    ('LIOPROPOMATIDAE'),
    ('PSILORHYNCHIDAE'),
    ('PLATYTROCTIDAE'),
    ('HORABAGRIDAE'),
    ('GEODIIDAE'),
    ('PALAEMONIDAE'),
    ('POECILIIDAE'),
    ('AGARICIIDAE'),
    ('PRIACANTHIDAE'),
    ('OCULINIDAE'),
    ('GYMNARCHIDAE'),
    ('DENDRONOTIDAE'),
    ('APLYSIIDAE'),
    ('HELIASTERIDAE'),
    ('MALAPTERURIDAE'),
    ('LETHRINIDAE'),
    ('LAMNIDAE'),
    ('LOBOTIDAE'),
    ('SPONDYLIDAE'),
    ('ANTEDONID');

-- fish
-- INSERT INTO fish (code_fao, name, latin_name, species_family_id)
-- VALUES ('ALB', 'Thon germon', 'Thunnus alalunga', 3);
-- INSERT INTO fish (code_fao, name, latin_name, species_family_id)
-- VALUES ('SFA', 'Espadon Voilier', 'Istiophorus platypterus', 4);
-- INSERT INTO fish (code_fao, name, latin_name, species_family_id)
-- VALUES ('RAJ', 'Raie', 'Raie', 2);
-- INSERT INTO fish (code_fao, name, latin_name, species_family_id)
-- VALUES ('SMA', 'Requin-taupe bleu', 'Isurus oxyrinchus', 1);

-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (1, 1, '1');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (1, 2, '1.11');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (1, 3, '1.11');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (1, 4, '1.2');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (1, 5, '1.76');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (1, 6, '1.94');

-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (2, 1, '1');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (2, 2, '1.18');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (2, 3, '1.18');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (2, 4, '1.3');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (2, 5, '1.84');
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (2, 6, '2.33');

-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (3, 1, 1);
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (3, 2, 1.13);
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (3, 3, 1.13);

-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (4, 1, 1);
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (4, 2, 1.15);
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (4, 3, 1.15);
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (4, 4, 1.3);
-- INSERT INTO coef_epv (fish_id, presentation_code, coef)
-- VALUES (4, 5, 1.41);
